export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_FAIL    = 'REGISTER_FAIL';

//
export const FORGOTPWD_SUCCESS = 'FORGOTPWD_SUCCESS';
export const FORGOTPWD_STARTED = 'FORGOTPWD_STARTED';
export const FORGOTPWD_FAIL    = 'FORGOTPWD_FAIL';